name: combined_app_task2

description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  hydrated_bloc: ^9.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.3+1
  intl: ^0.19.0
  # google_sign_in: ^6.2.1 # Uncomment if you plan to implement Google sign-in
  # Add google_sign_in if you plan to implement actual Google sign-in
  # google_sign_in: ^6.x.x
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
