// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChRATXDa6v6xiyRbIGXRue5blrm55REZs',
    appId: '1:133932690060:web:196cb5e12309e9d67ca9a9',
    messagingSenderId: '133932690060',
    projectId: 'fir-auth-task-2-5a221',
    authDomain: 'fir-auth-task-2-5a221.firebaseapp.com',
    storageBucket: 'fir-auth-task-2-5a221.firebasestorage.app',
    measurementId: 'G-XRCJJ6Z1V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5b-fvjD8Kj9mJzg-CahP7h4_mY-g7s_I',
    appId: '1:133932690060:android:97a735869d1a77417ca9a9',
    messagingSenderId: '133932690060',
    projectId: 'fir-auth-task-2-5a221',
    storageBucket: 'fir-auth-task-2-5a221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeBgKIYUlelsE5e-5KRiEYYKZ7hkloRKs',
    appId: '1:133932690060:ios:83431b1b5afb06ae7ca9a9',
    messagingSenderId: '133932690060',
    projectId: 'fir-auth-task-2-5a221',
    storageBucket: 'fir-auth-task-2-5a221.firebasestorage.app',
    androidClientId: '133932690060-thhoed19t9jl9hqlu5e14qnji2m28fbs.apps.googleusercontent.com',
    iosClientId: '133932690060-prm59m587leu2obe9f4g7snd4obo29co.apps.googleusercontent.com',
    iosBundleId: 'com.example.combinedAppTask2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeBgKIYUlelsE5e-5KRiEYYKZ7hkloRKs',
    appId: '1:133932690060:ios:83431b1b5afb06ae7ca9a9',
    messagingSenderId: '133932690060',
    projectId: 'fir-auth-task-2-5a221',
    storageBucket: 'fir-auth-task-2-5a221.firebasestorage.app',
    androidClientId: '133932690060-thhoed19t9jl9hqlu5e14qnji2m28fbs.apps.googleusercontent.com',
    iosClientId: '133932690060-prm59m587leu2obe9f4g7snd4obo29co.apps.googleusercontent.com',
    iosBundleId: 'com.example.combinedAppTask2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChRATXDa6v6xiyRbIGXRue5blrm55REZs',
    appId: '1:133932690060:web:bb908d1fcea17f777ca9a9',
    messagingSenderId: '133932690060',
    projectId: 'fir-auth-task-2-5a221',
    authDomain: 'fir-auth-task-2-5a221.firebaseapp.com',
    storageBucket: 'fir-auth-task-2-5a221.firebasestorage.app',
    measurementId: 'G-Y7J7V8WNZ1',
  );
}
